// Edit these four entries to update project names, descriptions, images and videos.
const projects = [
 {id:'little-spark',name:'HIMATEKKOM Visuals',category:'Editorial & event design',kind:'design',headline:'Stories from<br><em>campus life.</em>',summary:'A selection of my design work for HIMATEKKOM ITS: an event recap, a student information poster, and a football watch-party recap.',tags:['Graphic design','Editorial'],tools:'Layout · Typography · Photo compositing',process:'Each piece starts with the information people need to find. I use type, photos, and color to give it a clear order, then build a visual mood around the event.',assets:{Image:{src:'assets/benchmark-recap.webp',alt:'Benchmark HMTK x HIMATEKKOM event recap designed by Ilan',items:[{src:'assets/benchmark-recap.webp',thumb:'assets/benchmark-recap-thumb.webp',title:'Benchmark — event recap',alt:'Three-panel photo collage for Benchmark HMTK x HIMATEKKOM'},{src:'assets/risprof-center.webp',thumb:'assets/risprof-center-thumb.webp',title:'RISPROF Center — student information',alt:'Purple, cyan and orange RISPROF Center poster for internships, competitions and scholarships'},{src:'assets/anakonda-recap.webp',thumb:'assets/anakonda-recap-thumb.webp',title:'Anakonda 3 — Timnas Day recap',alt:'Football watch-party recap with a red and gold composition'}]}}},
 {id:'signal-lab',name:'AEROSENSE',category:'Air-quality dashboard prototype',kind:'engineering',headline:'Making air data<br><em>easier to read.</em>',summary:'An Indonesian dashboard prototype for Gresik, bringing sensor views, alerts, ESG reporting, and AERO-BOT into one interface.',tags:['Web prototype','AIoT'],tools:'JavaScript · Data visualization · Interface design',process:'I brought the monitoring views into one flow so readers can move from an area summary to a sensor, an alert, or a report. The current interface uses sample data; live telemetry and the assistant backend are the next steps.',status:'Interface prototype · sample sensor data',assets:{Image:{src:'https://raw.githubusercontent.com/ilanpr/Aerosense-Website/main/screenshots/beranda.jpg',alt:'AEROSENSE dashboard homepage',items:[{src:'https://raw.githubusercontent.com/ilanpr/Aerosense-Website/main/screenshots/beranda.jpg',title:'Area overview',alt:'AEROSENSE homepage with air-quality summary'},{src:'https://raw.githubusercontent.com/ilanpr/Aerosense-Website/main/screenshots/peta.jpg',title:'Sensor map',alt:'AEROSENSE sample sensor locations and readings'},{src:'https://raw.githubusercontent.com/ilanpr/Aerosense-Website/main/screenshots/aerobot.jpg',title:'AERO-BOT interface',alt:'AEROSENSE conversational assistant interface'}]},GitHub:{src:'https://github.com/ilanpr/Aerosense-Website'},Document:{src:'https://github.com/ilanpr/Aerosense-Website/tree/main/docs'}}},
 {id:'everyday-interface',name:'Spots',category:'Places, shared through stories',kind:'interface',headline:'Good places.<br><em>Real stories.</em>',summary:'A place-sharing app for finding food, cafés, and trips through other people’s experiences. The project is moving from a web interface to Flutter and Supabase.',tags:['Flutter','Product design'],tools:'Flutter · Supabase · Maps',process:'Photos, stories, and locations sit together so people can get a feel for a place before they visit. The screenshots show the earlier web interface that guides the Flutter version.',status:'Flutter project · earlier web interface shown',assets:{Image:{src:'https://raw.githubusercontent.com/ilanpr/Spots-Application/main/docs/images/landing-desktop.jpg',alt:'Spots web landing page',items:[{src:'https://raw.githubusercontent.com/ilanpr/Spots-Application/main/docs/images/landing-desktop.jpg',title:'Web design — landing page',alt:'Spots place-sharing landing page'},{src:'https://raw.githubusercontent.com/ilanpr/Spots-Application/main/docs/images/feed-mobile.jpg',title:'Web design — mobile feed',alt:'Spots mobile feed with place recommendations'},{src:'https://raw.githubusercontent.com/ilanpr/Spots-Application/main/docs/images/map-mobile.jpg',title:'Web design — mobile map',alt:'Spots map of shared places'}]},GitHub:{src:'https://github.com/ilanpr/Spots-Application'},Document:{src:'https://github.com/ilanpr/Spots-Application/blob/main/docs/PRODUCT.md'}}},
 {id:'type-in-motion',name:'Motion Studies',category:'Animation & video editing',kind:'motion',headline:'A little rhythm.<br><em>A different mood.</em>',summary:'Two of my motion projects: a music-player animation with a green visualizer, and a vertical explainer built around laptop components.',tags:['Motion graphics','Video editing'],tools:'Compositing · Timing · Visual storytelling',process:'The music-player study follows the track with a soft green glow and moving bars. The laptop explainer uses cutouts, changing scenes, and a vertical format to keep the story moving.',assets:{Image:{src:'assets/music-player-poster.webp',alt:'Frame from Ilan’s green music-player animation'},Video:{src:'assets/music-player-motion.mp4',items:[{src:'assets/music-player-motion.mp4',poster:'assets/music-player-poster.webp',title:'Music-player motion study',description:'A green music-player composition with an animated visualizer. 19 seconds.'},{src:'assets/laptop-explainer.mp4',poster:'assets/laptop-explainer-poster.webp',title:'Laptop explainer',description:'A vertical edit introducing laptop components. 1 minute 12 seconds.'}]}}}
];
const codeProjects=[{name:'Sword Slash Hunter',summary:'A webcam-controlled game using Python and OpenCV to turn hand movement into sword attacks.',url:'https://github.com/ilanpr/Sword-Slash-Hunter'},{name:'AEROSENSE',summary:'An air-quality dashboard interface with sample data.',url:'https://github.com/ilanpr/Aerosense-Website'},{name:'Spots',summary:'A place-sharing app moving to Flutter and Supabase.',url:'https://github.com/ilanpr/Spots-Application'}];
const profile = {name:'Ilan Hawwari Prasojo',github:'https://github.com/ilanpr',linkedin:'https://www.linkedin.com/in/ilanprasojo/'};
const dialog = document.querySelector('#project-dialog');
const dialogBody = document.querySelector('#dialog-body');
const reduceMotion = matchMedia('(prefers-reduced-motion: reduce)');
const escapeText=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function safeSrc(src){if(!src)return null;try{const u=new URL(src,location.href);return u.protocol==='https:'||(u.origin===location.origin&&u.protocol===location.protocol)?escapeText(u.href):null;}catch{return null;}}
function projectCover(p){return `<img class="work-cover" src="${safeSrc(p.assets.Image.src)}" alt="${escapeText(p.assets.Image.alt)}" loading="lazy">`;}
document.querySelector('#project-list').innerHTML=projects.map((p,i)=>`<article class="project reveal" id="${p.id}"><button class="project-visual" data-project="${p.id}" aria-label="View ${escapeText(p.name)}"><div class="project-stage ${p.kind}"><p class="cover-label">SELECTED WORK / 0${i+1}</p>${projectCover(p)}</div></button><div class="project-editorial"><p class="project-index mono">0${i+1} / ${p.category}</p><h3>${p.name}</h3><p>${p.summary}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><button class="editorial-open" data-project="${p.id}">View project <span aria-hidden="true">↗</span></button></div></article>`).join('');
function pauseDialogMedia(){dialogBody.querySelectorAll('video').forEach(video=>video.pause());}
function showDialog(){if(!dialog.open)dialog.showModal();document.body.classList.add('modal-open');}
function openProject(id,startTab='Overview'){
 const p=projects.find(p=>p.id===id);if(!p)return;pauseDialogMedia();
 const tabs=['Overview',...Object.keys(p.assets)];if(!tabs.includes(startTab))startTab='Overview';
 dialogBody.innerHTML=`<div class="dialog-header"><p class="mono">${p.category.toUpperCase()} / SELECTED WORK</p><h2 id="dialog-title">${p.name}</h2></div><div class="dialog-content"><p>${p.summary}</p>${p.status?`<p class="status-note">${p.status}</p>`:''}<div class="modal-tabs" role="tablist" aria-label="Project details">${tabs.map(t=>`<button id="tab-${t}" role="tab" aria-selected="${t===startTab}" aria-controls="asset-content" tabindex="${t===startTab?0:-1}" data-tab="${t}">${t==='Document'?'Notes':t==='Image'?'Images':t==='Video'?'Videos':t}</button>`).join('')}</div><div class="asset-panel" id="asset-content" role="tabpanel" tabindex="0"></div></div>`;
 dialogBody.dataset.project=id;renderTab(startTab);showDialog();
}
function renderTab(type,index=0){
 const p=projects.find(p=>p.id===dialogBody.dataset.project),panel=document.querySelector('#asset-content');if(!p||!panel)return;pauseDialogMedia();
 document.querySelectorAll('[data-tab]').forEach(b=>{b.setAttribute('aria-selected',String(b.dataset.tab===type));b.tabIndex=b.dataset.tab===type?0:-1;});panel.setAttribute('aria-labelledby',`tab-${type}`);
 const asset=p.assets[type],url=safeSrc(asset?.src);
 if(type==='Overview')panel.innerHTML=`<h3>About the project</h3><p>${p.process}</p><p class="project-tools">${p.tools}</p><button class="overview-image" data-tab="${p.assets.Video?'Video':'Image'}">${projectCover(p)}<span>Explore ${p.assets.Video?'the videos':'the images'} <span aria-hidden="true">↗</span></span></button>`;
 else if(type==='Image'){
  const items=asset.items||[asset],item=items[Math.max(0,Math.min(index,items.length-1))];
  panel.innerHTML=`<figure class="image-view"><img src="${safeSrc(item.src)}" alt="${escapeText(item.alt||p.name)}"><figcaption>${escapeText(item.title||p.name)}</figcaption><a href="${safeSrc(item.src)}" target="_blank" rel="noopener noreferrer">Open full image ↗</a></figure>${items.length>1?`<div class="gallery-thumbs" aria-label="Choose an image">${items.map((im,i)=>`<button data-gallery-index="${i}" aria-pressed="${i===index}"><img src="${safeSrc(im.thumb||im.src)}" alt="" loading="lazy"><span>${escapeText(im.title)}</span></button>`).join('')}</div>`:''}`;
 }else if(type==='Video')panel.innerHTML=`<div class="video-gallery">${(asset.items||[asset]).map(item=>`<figure><video controls playsinline preload="none" poster="${safeSrc(item.poster)}" src="${safeSrc(item.src)}" aria-label="${escapeText(item.title)}"></video><figcaption><h3>${escapeText(item.title)}</h3><p>${escapeText(item.description||'')}</p></figcaption></figure>`).join('')}</div>`;
 else if(type==='GitHub')panel.innerHTML=`<h3>Explore the code</h3><p>${p.process}</p><a class="pill yellow" href="${url}" target="_blank" rel="noopener noreferrer">Open repository ↗</a>`;
 else if(type==='Document')panel.innerHTML=`<h3>Project notes</h3><p>${p.process}</p><a class="pill yellow" href="${url}" target="_blank" rel="noopener noreferrer">Read documentation ↗</a>`;
}
document.addEventListener('click',e=>{
 const project=e.target.closest('[data-project]');if(project)openProject(project.dataset.project,project.dataset.startTab||'Overview');
 const tab=e.target.closest('[data-tab]');if(tab)renderTab(tab.dataset.tab);
 const thumb=e.target.closest('[data-gallery-index]');if(thumb)renderTab('Image',Number(thumb.dataset.galleryIndex));
 const folder=e.target.closest('[data-archive]');if(folder){pauseDialogMedia();const type=folder.dataset.archive;
  dialogBody.innerHTML=`<div class="dialog-header"><p class="mono">THE ARCHIVE</p><h2 id="dialog-title">${folder.querySelector('b').textContent}</h2></div><div class="dialog-content"><div class="archive-list">${type==='GitHub'?codeProjects.map(p=>`<a href="${p.url}" target="_blank" rel="noopener noreferrer"><span><b>${p.name}</b><small>${p.summary}</small></span><span aria-hidden="true">↗</span></a>`).join(''):projects.filter(p=>p.assets[type]).map(p=>`<button data-project="${p.id}" data-start-tab="${type}"><span><b>${p.name}</b><small>${p.category}</small></span><span class="mono">OPEN ↗</span></button>`).join('')}</div></div>`;showDialog();
 }
});
document.addEventListener('keydown',e=>{if(!e.target.matches('[role="tab"]'))return;const tabs=[...document.querySelectorAll('[role="tab"]')];let i=tabs.indexOf(e.target);if(e.key==='ArrowRight')i=(i+1)%tabs.length;else if(e.key==='ArrowLeft')i=(i-1+tabs.length)%tabs.length;else if(e.key==='Home')i=0;else if(e.key==='End')i=tabs.length-1;else return;e.preventDefault();renderTab(tabs[i].dataset.tab);tabs[i].focus();});
document.addEventListener('play',event=>{if(event.target.tagName==='VIDEO')document.querySelectorAll('video').forEach(video=>{if(video!==event.target)video.pause();});},true);
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{pauseDialogMedia();document.body.classList.remove('modal-open');});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
document.querySelector('#contact-button').addEventListener('click',()=>{pauseDialogMedia();dialogBody.innerHTML=`<div class="dialog-header"><p class="mono">LET’S CONNECT</p><h2 id="dialog-title">Say hello.</h2></div><div class="dialog-content"><p>I’m open to student projects, creative collaborations, and internship opportunities. You can find me on LinkedIn or explore what I’m working on through GitHub.</p><div class="contact-links"><a class="pill yellow" href="${profile.linkedin}" target="_blank" rel="noopener noreferrer">Connect on LinkedIn ↗</a><a class="pill dark" href="${profile.github}" target="_blank" rel="noopener noreferrer">Explore GitHub ↗</a></div></div>`;showDialog();});
const motionButton=document.querySelector('.motion-toggle');function setMotion(paused){document.body.classList.toggle('paused',paused);motionButton.textContent=paused?'Play motion':'Pause motion';motionButton.setAttribute('aria-pressed',String(paused));}motionButton.addEventListener('click',()=>setMotion(!document.body.classList.contains('paused')));
function updateMotionPreference(){document.body.classList.toggle('has-motion',!reduceMotion.matches);if(reduceMotion.matches)setMotion(true);}updateMotionPreference();reduceMotion.addEventListener('change',updateMotionPreference);
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.querySelectorAll('.section-title,.about-art,.about-copy,.folders,footer h2').forEach(el=>{el.classList.add('motion-enter');observer.observe(el);});
document.querySelectorAll('.project-visual').forEach(visual=>{
 const stage=visual.querySelector('.project-stage');
 const look=(x,y)=>{stage.style.setProperty('--project-look-x',x+'px');stage.style.setProperty('--project-look-y',y+'px');stage.style.setProperty('--project-title-x',-x*.28+'px');stage.style.setProperty('--project-title-y',-y*.28+'px');};
 visual.addEventListener('pointermove',event=>{
  if(event.pointerType!=='mouse'||reduceMotion.matches||document.body.classList.contains('paused'))return;
  const box=visual.getBoundingClientRect();look(((event.clientX-box.left)/box.width-.5)*20,((event.clientY-box.top)/box.height-.5)*16);
 });
 visual.addEventListener('pointerleave',()=>look(0,0));
});
let scheduled=false;function updateScroll(){scheduled=false;const max=document.documentElement.scrollHeight-innerHeight;document.querySelector('.progress').style.width=(max>0?scrollY/max*100:0)+'%';}
addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(updateScroll);}},{passive:true});updateScroll();document.addEventListener('visibilitychange',()=>document.querySelectorAll('.ticker>div,.motion-demo span,.cartridge-art img,.pixel-particle').forEach(el=>el.style.animationPlayState=document.hidden?'paused':''));
